# Server settings (ServerProperties)
server:
  port: 8081
  address: localhost
spring:
  cloud:
    client:
      ipAddress: 127.0.0.1
  application:
    name: zuul
eureka:
  instance:
    hostname: ${spring.cloud.client.ipAddress}
    preferIpAddress:  false
    ipAddress: 127.0.0.1
    instance-id:  ${spring.cloud.client.ipAddress}:${server.port}
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/
zuul:
  routes:
    user_user:
      path: /user/**
      serviceId: user
      stripPrefix: false  # forward /usr/** to user service /user/**
    user_register:
      path: /register/**
      serviceId: user
      stripPrefix: false
    community:
      path: /community/**
      serviceId: community
      stripPrefix: false