server:
  port: 8080
eureka:
  instance:
    preferIpAddress:  true
    instance-id:  ${spring.cloud.client.ipAddress}:${server.port}
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/